module.exports = {
  semi: true,
  tabWidth: 2,
  printWidth: 100,
  singleQuote: true,
  jsxSingleQuote: true,
  trailingComma: 'es5',
  jsxBracketSameLine: true,
  arrowParens: 'always',
  bracketSpacing: true,
  singleAttributePerLine: false,
  endOfLine: 'lf',
  htmlWhitespaceSensitivity: 'css',
  proseWrap: 'preserve',
  quoteProps: 'as-needed',
  insertPragma: false,
  requirePragma: false,
  useTabs: false,
  plugins: [require('prettier-plugin-tailwindcss')],
};
